//特权说明弹出框
$(function(){
	$("#powIntro").on('touchstart',function(event){
		event.preventDefault();
		$(".mask").fadeIn();
	});
	if($(".mask").length > 0){
		$("#close").on('touchstart',function(event){
			event.preventDefault();
			$(".mask").fadeOut();
		})
	}
})
//积分明细弹出框
$(function(){
	$("#allScore").on('touchstart',function(event){
		event.preventDefault();
		$(".detailMask").fadeIn();
	});
	if($(".detailMask").length > 0){
		$("#closetwo").on('touchstart',function(){
			$(".detailMask").fadeOut();
		})
	}
})
// 点击侧边栏按钮
$(function(){
	$("#navbtn").on('touchstart',function(event){
		event.preventDefault();
		$(".navmask").fadeIn().siblings('.navselect').fadeIn();
	});
	$(".navmask").on('touchstart',function(event){
		$(this).fadeOut().siblings('.navselect').fadeOut();
	});
})
//链接跳转点击元素对应显现背景色
$(".navselect").on('touchstart','.bgc',function(){
	//event.preventDefault();
	$(this).addClass('active').siblings().removeClass('active');
})